### ISSUE TITLE
Which data file refers to Latvian / Lithuanian ?

### ISSUE THREAD

**Issue by thangld201** [accurat-toolkit/TildeNER#1]
Hi @arne-cl, I am looking at the manually annotated data in https://github.com/accurat-toolkit/TildeNER/blob/master/TEST/gold_tab_sep_in, but I do not see any separation between texts from two languages (Latvian / Lithuanian) ?

**Comment by arne-cl** [comment]
Dear @thangld201,

I have never worked with the data. My motivation to put it on Github was that I don't trust these EU funded projects to keep their websites running after the project ends. Luckily, the site is still up, so you will hopefully get an answer from the original authors there: http://www.accurat-project.eu/ .

Best of luck,
Arne
